# Generated by Django 4.0.1 on 2022-02-17 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exeterDomination', '0002_remove_users_possession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='claimedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exeterDomination.users'),
        ),
    ]
