# Generated by Django 4.0.1 on 2022-02-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exeterDomination', '0003_alter_locations_claimedby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='latitude',
            new_name='p1Latitude',
        ),
        migrations.RenameField(
            model_name='locations',
            old_name='longitude',
            new_name='p1Longitude',
        ),
        migrations.AddField(
            model_name='locations',
            name='p2Latitude',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locations',
            name='p2Longitude',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
