# Generated by Django 4.0.1 on 2022-02-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exeterDomination', '0004_rename_latitude_locations_p1latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoOrds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='locations',
            name='p1Latitude',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='p1Longitude',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='p2Latitude',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='p2Longitude',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AddField(
            model_name='locations',
            name='blCoOrd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottomLeft', to='exeterDomination.coords'),
        ),
        migrations.AddField(
            model_name='locations',
            name='trCoOrd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topRigh', to='exeterDomination.coords'),
        ),
        migrations.AddField(
            model_name='users',
            name='lastPos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exeterDomination.coords'),
        ),
    ]
