# Generated by Django 4.0.1 on 2022-02-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exeterDomination',
         '0005_coords_remove_locations_p1latitude_and_more'), ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='lastPos',
        ),
    ]
