# Generated by Django 4.0.1 on 2022-02-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exeterDomination', '0007_alter_locations_claimedby_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='coords',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
