# Generated by Django 4.0.1 on 2022-02-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exeterDomination',
         '0008_alter_coords_latitude_alter_coords_longitude'), ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='coords',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
