# Generated by Django 4.0.3 on 2022-03-18 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exeterDomination',
         '0009_alter_coords_latitude_alter_coords_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='blCoOrd',
            new_name='bottomLeftCoordinate',
        ),
        migrations.RenameField(
            model_name='locations',
            old_name='trCoOrd',
            new_name='topRightCoordinate',
        ),
    ]
