# Generated by Django 4.0.3 on 2022-03-19 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exeterDomination', '0010_rename_blcoord_locations_bottomleftcoordinate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coords',
            options={'verbose_name': 'Coordinate', 'verbose_name_plural': 'Coordinates'},
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterField(
            model_name='locations',
            name='bottomLeftCoordinate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottomLeft', to='exeterDomination.coords', verbose_name='Bottom Left Coordinate'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='claimedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Claimed By'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='topRightCoordinate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topRigh', to='exeterDomination.coords', verbose_name='Top Right Coordinate'),
        ),
    ]
